/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as JoinTheCommunityRouteImport } from './routes/join-the-community'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RecordingPolicyRouteImport } from './routes/recording-policy'
import { Route as SponsorsPartnersRouteImport } from './routes/sponsors-partners'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AudioSlugRouteImport } from './routes/audio.$slug'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as CollectionsLabelRouteImport } from './routes/collections.$label'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as FilmsIndexRouteImport } from './routes/films.index'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as ArticleCategoryCategoryRouteImport } from './routes/article.category.$category'
import { Route as ArticleTagTagRouteImport } from './routes/article.tag.$tag'
import { Route as ApiPublicStreamLicenseRouteImport } from './routes/api/public/stream.license'
import { Route as ApiPublicStreamManifestRouteImport } from './routes/api/public/stream.manifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTheCommunityRoute = JoinTheCommunityRouteImport.update({
  id: '/join-the-community',
  path: '/join-the-community',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingPolicyRoute = RecordingPolicyRouteImport.update({
  id: '/recording-policy',
  path: '/recording-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsPartnersRoute = SponsorsPartnersRouteImport.update({
  id: '/sponsors-partners',
  path: '/sponsors-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioSlugRoute = AudioSlugRouteImport.update({
  id: '/audio/$slug',
  path: '/audio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsLabelRoute = CollectionsLabelRouteImport.update({
  id: '/collections/$label',
  path: '/collections/$label',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmsRoute,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FilmsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideosRoute,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleCategoryCategoryRoute = ArticleCategoryCategoryRouteImport.update({
  id: '/article/category/$category',
  path: '/article/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleTagTagRoute = ArticleTagTagRouteImport.update({
  id: '/article/tag/$tag',
  path: '/article/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamLicenseRoute = ApiPublicStreamLicenseRouteImport.update({
  id: '/api/public/stream/license',
  path: '/api/public/stream/license',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamManifestRoute = ApiPublicStreamManifestRouteImport.update({
  id: '/api/public/stream/manifest',
  path: '/api/public/stream/manifest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/films': typeof FilmsRouteWithChildren
  '/join-the-community': typeof JoinTheCommunityRoute
  '/library': typeof LibraryRoute
  '/podcast': typeof PodcastRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recording-policy': typeof RecordingPolicyRoute
  '/sponsors-partners': typeof SponsorsPartnersRoute
  '/subscribe': typeof SubscribeRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/audio/$slug': typeof AudioSlugRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/collections/$label': typeof CollectionsLabelRoute
  '/event/$slug': typeof EventSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/films/': typeof FilmsIndexRoute
  '/article/category/$category': typeof ArticleCategoryCategoryRoute
  '/article/tag/$tag': typeof ArticleTagTagRoute
  '/api/public/stream/license': typeof ApiPublicStreamLicenseRoute
  '/api/public/stream/manifest': typeof ApiPublicStreamManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/join-the-community': typeof JoinTheCommunityRoute
  '/library': typeof LibraryRoute
  '/podcast': typeof PodcastRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recording-policy': typeof RecordingPolicyRoute
  '/sponsors-partners': typeof SponsorsPartnersRoute
  '/subscribe': typeof SubscribeRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/audio/$slug': typeof AudioSlugRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/collections/$label': typeof CollectionsLabelRoute
  '/event/$slug': typeof EventSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/films': typeof FilmsIndexRoute
  '/article/category/$category': typeof ArticleCategoryCategoryRoute
  '/article/tag/$tag': typeof ArticleTagTagRoute
  '/api/public/stream/license': typeof ApiPublicStreamLicenseRoute
  '/api/public/stream/manifest': typeof ApiPublicStreamManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/films': typeof FilmsRouteWithChildren
  '/join-the-community': typeof JoinTheCommunityRoute
  '/library': typeof LibraryRoute
  '/podcast': typeof PodcastRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recording-policy': typeof RecordingPolicyRoute
  '/sponsors-partners': typeof SponsorsPartnersRoute
  '/subscribe': typeof SubscribeRoute
  '/team': typeof TeamRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/audio/$slug': typeof AudioSlugRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/collections/$label': typeof CollectionsLabelRoute
  '/event/$slug': typeof EventSlugRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/films/': typeof FilmsIndexRoute
  '/article/category/$category': typeof ArticleCategoryCategoryRoute
  '/article/tag/$tag': typeof ArticleTagTagRoute
  '/api/public/stream/license': typeof ApiPublicStreamLicenseRoute
  '/api/public/stream/manifest': typeof ApiPublicStreamManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/board'
    | '/contact'
    | '/courses'
    | '/events'
    | '/faq'
    | '/films'
    | '/join-the-community'
    | '/library'
    | '/podcast'
    | '/privacy-policy'
    | '/recording-policy'
    | '/sponsors-partners'
    | '/subscribe'
    | '/team'
    | '/testimonials'
    | '/videos'
    | '/article/$slug'
    | '/audio/$slug'
    | '/checkout/$planId'
    | '/collections/$label'
    | '/event/$slug'
    | '/films/$slug'
    | '/products/$slug'
    | '/videos/$slug'
    | '/watch/$slug'
    | '/films/'
    | '/article/category/$category'
    | '/article/tag/$tag'
    | '/api/public/stream/license'
    | '/api/public/stream/manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/articles'
    | '/board'
    | '/contact'
    | '/courses'
    | '/events'
    | '/faq'
    | '/join-the-community'
    | '/library'
    | '/podcast'
    | '/privacy-policy'
    | '/recording-policy'
    | '/sponsors-partners'
    | '/subscribe'
    | '/team'
    | '/testimonials'
    | '/videos'
    | '/article/$slug'
    | '/audio/$slug'
    | '/checkout/$planId'
    | '/collections/$label'
    | '/event/$slug'
    | '/films/$slug'
    | '/products/$slug'
    | '/videos/$slug'
    | '/watch/$slug'
    | '/films'
    | '/article/category/$category'
    | '/article/tag/$tag'
    | '/api/public/stream/license'
    | '/api/public/stream/manifest'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/board'
    | '/contact'
    | '/courses'
    | '/events'
    | '/faq'
    | '/films'
    | '/join-the-community'
    | '/library'
    | '/podcast'
    | '/privacy-policy'
    | '/recording-policy'
    | '/sponsors-partners'
    | '/subscribe'
    | '/team'
    | '/testimonials'
    | '/videos'
    | '/article/$slug'
    | '/audio/$slug'
    | '/checkout/$planId'
    | '/collections/$label'
    | '/event/$slug'
    | '/films/$slug'
    | '/products/$slug'
    | '/videos/$slug'
    | '/watch/$slug'
    | '/films/'
    | '/article/category/$category'
    | '/article/tag/$tag'
    | '/api/public/stream/license'
    | '/api/public/stream/manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArticlesRoute: typeof ArticlesRoute
  BoardRoute: typeof BoardRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  FilmsRoute: typeof FilmsRouteWithChildren
  JoinTheCommunityRoute: typeof JoinTheCommunityRoute
  LibraryRoute: typeof LibraryRoute
  PodcastRoute: typeof PodcastRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RecordingPolicyRoute: typeof RecordingPolicyRoute
  SponsorsPartnersRoute: typeof SponsorsPartnersRoute
  SubscribeRoute: typeof SubscribeRoute
  TeamRoute: typeof TeamRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VideosRoute: typeof VideosRouteWithChildren
  ArticleSlugRoute: typeof ArticleSlugRoute
  AudioSlugRoute: typeof AudioSlugRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  CollectionsLabelRoute: typeof CollectionsLabelRoute
  EventSlugRoute: typeof EventSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ArticleCategoryCategoryRoute: typeof ArticleCategoryCategoryRoute
  ArticleTagTagRoute: typeof ArticleTagTagRoute
  ApiPublicStreamLicenseRoute: typeof ApiPublicStreamLicenseRoute
  ApiPublicStreamManifestRoute: typeof ApiPublicStreamManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-the-community': {
      id: '/join-the-community'
      path: '/join-the-community'
      fullPath: '/join-the-community'
      preLoaderRoute: typeof JoinTheCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording-policy': {
      id: '/recording-policy'
      path: '/recording-policy'
      fullPath: '/recording-policy'
      preLoaderRoute: typeof RecordingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors-partners': {
      id: '/sponsors-partners'
      path: '/sponsors-partners'
      fullPath: '/sponsors-partners'
      preLoaderRoute: typeof SponsorsPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/$slug': {
      id: '/audio/$slug'
      path: '/audio/$slug'
      fullPath: '/audio/$slug'
      preLoaderRoute: typeof AudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$label': {
      id: '/collections/$label'
      path: '/collections/$label'
      fullPath: '/collections/$label'
      preLoaderRoute: typeof CollectionsLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof VideosRoute
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/category/$category': {
      id: '/article/category/$category'
      path: '/article/category/$category'
      fullPath: '/article/category/$category'
      preLoaderRoute: typeof ArticleCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/tag/$tag': {
      id: '/article/tag/$tag'
      path: '/article/tag/$tag'
      fullPath: '/article/tag/$tag'
      preLoaderRoute: typeof ArticleTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/license': {
      id: '/api/public/stream/license'
      path: '/api/public/stream/license'
      fullPath: '/api/public/stream/license'
      preLoaderRoute: typeof ApiPublicStreamLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/manifest': {
      id: '/api/public/stream/manifest'
      path: '/api/public/stream/manifest'
      fullPath: '/api/public/stream/manifest'
      preLoaderRoute: typeof ApiPublicStreamManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilmsRouteChildren {
  FilmsSlugRoute: typeof FilmsSlugRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsSlugRoute: FilmsSlugRoute,
  FilmsIndexRoute: FilmsIndexRoute,
}

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren)

interface VideosRouteChildren {
  VideosSlugRoute: typeof VideosSlugRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosSlugRoute: VideosSlugRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArticlesRoute: ArticlesRoute,
  BoardRoute: BoardRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  FilmsRoute: FilmsRouteWithChildren,
  JoinTheCommunityRoute: JoinTheCommunityRoute,
  LibraryRoute: LibraryRoute,
  PodcastRoute: PodcastRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RecordingPolicyRoute: RecordingPolicyRoute,
  SponsorsPartnersRoute: SponsorsPartnersRoute,
  SubscribeRoute: SubscribeRoute,
  TeamRoute: TeamRoute,
  TestimonialsRoute: TestimonialsRoute,
  VideosRoute: VideosRouteWithChildren,
  ArticleSlugRoute: ArticleSlugRoute,
  AudioSlugRoute: AudioSlugRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  CollectionsLabelRoute: CollectionsLabelRoute,
  EventSlugRoute: EventSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ArticleCategoryCategoryRoute: ArticleCategoryCategoryRoute,
  ArticleTagTagRoute: ArticleTagTagRoute,
  ApiPublicStreamLicenseRoute: ApiPublicStreamLicenseRoute,
  ApiPublicStreamManifestRoute: ApiPublicStreamManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
